"""empty message

Revision ID: 425db73d0f6a
Revises: 2073c1e6f97a
Create Date: 2025-03-13 23:38:24.071619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425db73d0f6a'
down_revision = '2073c1e6f97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
